version: '3.1'

services:
  cdc_mysql:
#    image: mysql:5.7.37 #amd
    image: ndhai/mysql:5.7 #arm
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: identity
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
